---
title: "report"
author: "Jose Munoz Angulo, Vivien Marcault, Baptiste Rigondaud"
date: "February 26, 2018"
output: html_document
---

## Question 1

The map is produced with this code:

//TODO: insert here

The map is created by extracting all unique indigenous population along with its latitude and longitude. By the means of the maps library we draw the map with the populations in its location, using 9 different colors and three different symbols.

## Question 2

Performing the linear regression:

// TODO: insert code here

R can not invert the matrix to solve te linear regression problem, because of the size of the matrix. Thus, it explains why the lieanr regression summary is full of Not A Number. In order to have a correct model, we could take a subset of the predictors using this command:

//TODO: insert code here

In the following questions, we are going to use PCA.

## Question 3

### a)
This method consist into diagonalizing the covariance matrix in order to find its maximum eigenvalues. These values correspond to the components of maximum variance. Therefore if we make a projection of the data on the factorspace generated by the corresponding eigenvectors, we preserve the maximum information that we can have from the original data in this dimension. 